version: "3"

env:
  # Platform specific DSN (since it's file-based and this project uses XDG).
  # Example for mac:
  DSN: "file:///Users/brodie.westrope/Library/Application Support/flower/sqlite.db"

tasks:
  codegen:
    cmds:
      - jet -source=sqlite -dsn="$DSN" -path=./gen

  migrate:
    cmds:
      - atlas schema apply -u "sqlite://$DSN" --to file://schema.hcl
      # atlas schema inspect -u "sqlite://$DSN" --format "{{ sql . }}"
